[model]
package = "bonito.crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[qscore]
bias = -0.7554
scale = 0.8555

[encoder]
stride = 6
winlen = 19
scale = 5.0
features = 128
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0

[global_norm]
state_len = 3

[basecaller]
batchsize = 1536
chunksize = 12000
overlap = 600
quantize = false
